
const assets = {
    banner: require("@/assets/banner.png"),
    empty: require("@/assets/empty.png"),
    vip: require("@/assets/vip.png"),
    userImg: require("@/assets/user-img.png"),
    fontfamily1: require("@/assets/fontfamily1.png"),
    fontfamily2: require("@/assets/fontfamily2.png"),
    fontfamily3: require("@/assets/fontfamily3.png"),
    fontfamily4: require("@/assets/fontfamily4.png"),
    fontfamily5: require("@/assets/fontfamily5.png"),
    fontfamily6: require("@/assets/fontfamily6.png"),
    fontfamily7: require("@/assets/fontfamily7.png"),
    fontfamily8: require("@/assets/fontfamily8.png"),
    fontfamily9: require("@/assets/fontfamily9.png"),
    fontfamily10: require("@/assets/fontfamily10.png"),
    recharge1: require("@/assets/recharge1.png"),
    recharge2: require("@/assets/recharge2.png"),
    recharge3: require("@/assets/recharge3.png"),
    energy: require("@/assets/energy.png"),
    emptyH: require("@/assets/empty-h.png"),
    emptyC: require("@/assets/empty-c.png"),
    actor: require("@/assets/actor.png"),
    ai1: require("@/assets/ai1.png"),
    ai2: require("@/assets/ai2.png"),
    avatar: require("@/assets/avatar.png"),
    avatar1: require("@/assets/avatar1.png"),
    setIcon: require("@/assets/set-icon.png"),
    unfoldIcon: require("@/assets/unfold-icon.png"),
    foldIcon: require("@/assets/fold-icon.png"),
    closeIcon: require("@/assets/close-icon.png"),
    logo: require("@/assets/logo.png"),
    logout: require("@/assets/logout.png"),
    logoVersion: require("@/assets/logo-version.png"),
    wechat: require("@/assets/wechat.png"),
    serviceCode: require("@/assets/service-code.png")
}

export default assets